### PR TITLE
ZHW makes files can be opened in GNU/Linux distributions.

### PR DESCRIPTION
**Pull request by wi24rd**
close #14

### CODE REVIEW

**Comment by salmonb** [comment]
I merged your PR, thank you!

You can now update your cli with `webfx bump cli`

FYI, you didn't need to create a new PR, you could simply push your changes on the same branch, this would have updated your previous PR, but maybe you're not familiar with PRs.

Anyway, thank you for your contribution! 🙏

**Comment by wi24rd** [comment]
I know I can just make a new commit.
But it seems like you would like have only one commit.
So I tried git commit --amend, however the remote branch can't be deleted
or pushed forcely, so I create a new branch.

On Wednesday, October 30, 2024, Bruno Salmon ***@***.***>
wrote:
> I merged your PR, thank you!
>
> You can now update your cli with webfx bump cli
>
> FYI, you didn't need to create a new PR, you could simply push your
changes on the same branch, this would have updated your previous PR, but
maybe you're not familiar with PRs.
>
> Anyway, thank you for your contribution! 🙏
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID:
***@***.***>

-- 
Computer Engineer
https://zhw.pages.dev/ <https://github.com/wi24rd>

**Comment by wi24rd** [comment]
How about using following code in multiple platform?
```
File currentDir = new File(System.getProperty("user.dir"));
File indexHtmlFile = new File(currentDir, "./index.html");
URI uri = indexHtmlFile.toURI();
java.awt.Desktop.getDesktop().browse(uri);
```

**Comment by wi24rd** [comment]
> How about using following code in multiple platform?
> 
> ```
> File currentDir = new File(System.getProperty("user.dir"));
> File indexHtmlFile = new File(currentDir, "./index.html");
> URI uri = indexHtmlFile.toURI();
> java.awt.Desktop.getDesktop().browse(uri);
> ```

We can directly call
java.awt.Desktop.getDesktop().open(indexHtmlFile)

**Comment by salmonb** [comment]
Thanks for your proposition, I tried Desktop.getDesktop().open() in the latest CLI version, let me know if it works on your Linux computer too.

**Pull request merged**
